name: 'Build, update and push to GCP's Container Registry'
description: 'Generic action to install node dependencies, build, test, update version and push docker image to GCP's Container Registry using Workload Identity Federation for authentication'

inputs:
  token:
    description: 'GitHub access token'
    required: true
    default: ${{ github.token }}
  checkout_branch:
    description: 'Branch to checkout'
    required: false
  snyk_token:
    description: 'Snyk token'
    required: false
  use_snyk:
    description: 'Using Snyk or not'
    type: string
    required: true
    default: true
  perform_tests:
    description: 'Perform unit tests or not'
    type: string
    required: true
    default: true
  npm_registry:
    description: 'NPM registry URL'
    required: true
    default: https://npm.pkg.github.com/
  npm_registry_scope:
    description: 'NPM registry scope'
    required: true
  docker_login_registry:
    description: 'Docker login registry'
    required: true
    default: ghcr.io
  docker_login_user:
    description: 'Docker login username'
    required: true
    default: ${{ github.actor }}
  ghcr_tag_owner:
    description: 'ghcr.io org. name (owner)'
    required: true
    default: ${{ github.repository_owner }}    
  docker_image_name:
    description: 'Docker image name'
    required: true
    default: ${{ github.event.repository.name }}     

outputs:
  tagversion:
    description: "updated version updated in package.json"
    value: ${{ steps.package-version.outputs.current-version }}
  imagename:
    description: "repository name"
    value: ${{ github.event.repository.name }}
   
permissions:
  contents: 'read'
  id-token: 'write'
  packages: 'write'
  
runs:
  using: "composite"  
  
  steps:
    # actions/checkout MUST come before auth
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'my-service-account@my-project.iam.gserviceaccount.com'

    # ... further steps are automatically authenticated
